Cargo.toml
Just to prove that no-std Move crates are compatible with Substrate
=> chore: include one no-std Move compatible crate

Cargo.toml, src/lib.rs, src/storage.rs
This code adds storage items for the pallet (StorageMap). Moreover, it adds impl block for the Move storage for the current Pallet with our configuration.
That PR contains a complementary Storage module based on Pontem's solution. Currently, it implements the main Move storage trait and storage adapter. Both are used to create storage impl for Pallet, as mentioned above.
That's initial support of storage, as it needs to be initialized when a real VM is created inside the pallet.
=> feat: runtime storage

Cargo.toml, src/lib.rs, tests/assets/move/sources/Empty.move, tests/modules.rs
Added functions which execute appropriate calls in the move-vm-backend providing:
- getting module bytecode
- getting resources from the module
- getting module ABI (not implemented on the backend side)
Note: get_resource call is returning Ok(None) even for the resource which should exist. Currently ignoring the test, but need to be investigated further, after it will be fixed in the backend.
=> feat: handling get_module*/get_resource calls

Cargo.toml, src/lib.rs
The provided gas for Move operations will be provided via the GasStrategy API to the backend layer.
=> chore: adapt to gas API changes in the move-vm-backend

doc/design.md, src/benchmarking.rs, src/lib.rs, src/weights.rs
- Allow publishing module bundles
- Renaming package to bundle
- So, for a set of modules, we'll use the term bundle instead of package(which can interfere with a Module Package term)
TODO:
- tests for this extrinsic
=> feat: impl publish_module_bundle

Cargo.toml, rpc/Cargo.toml, rpc/runtime-api/Cargo.toml, rpc/runtime-api/src/lib.rs, rpc/src/lib.rs, src/lib.rs, src/transaction.rs, tests/execute.rs, tests/mock.rs
- Bumping the polkasdk in the pallet from
`release-polkadot-v1.0.0` to `release-polkadot-v1.4.0`.
- `type Currency` added to `frame_system::Config`
- one other commit included: `chore: fix execute tests with some gas`
=>  deps: use release-polkadot-v1.4.0 

.github/workflows/common.yml
Run the test on each PR with:
`cargo test --verbose --features build-move-projects-for-test`
The Move projects in `tests/assets/move-projects` are not by default built when running `cargo test` since recompiling the same Move projects takes too much time.
=> ci: run tests on each run 

rpc/runtime-api/src/lib.rs, rpc/src/lib.rs, src/balance.rs, src/lib.rs, src/signer.rs
Gas script-execution estimation requires only three parameters:
- `account` (simulating the account that will sign the extrinsic)
- `transaction` (blob packed with necessary script parameters and the script bytecode)
- `cheque_limit` (simulation for balance status access without write rights)
Included in this change:
- updates to RPC modules
- prepared `raw_execute_script', which can be called from the runtime RPC module in a read_only fashion.
=> feat: enable estimate gas for script execution

doc/tech_guide.md
Update the directory for docker command execution to build a docker template-node image.
=> doc: correct details on docker instructions

tests/assets/move-projects/multiple-signers/Move.toml, tests/assets/move-projects/multiple-signers/build.sh, tests/assets/move-projects/multiple-signers/estimate.sh, tests/assets/move-projects/multiple-signers/sources/Dorm.move, tests/assets/move-projects/multiple-signers/sources/Scripts.move
To test script executions with multiple signers, a new move-project is needed. This PR adds such a project.
=> feat: add move-project for multiple signers

Cargo.toml, tests/assets/move-projects/smove-build-all.sh, tests/assets/move-projects/smove-clean-all.sh, tests/assets/move-projects/testing-move-stdlib/Move.toml, tests/assets/move-projects/testing-move-stdlib/README.md, tests/assets/move-projects/testing-move-stdlib/sources/ascii.move, tests/assets/move-projects/testing-move-stdlib/sources/bcs.move, tests/assets/move-projects/testing-move-stdlib/sources/bit_vector.move, tests/assets/move-projects/testing-move-stdlib/sources/error.move, tests/assets/move-projects/testing-move-stdlib/sources/fixed_point32.move, tests/assets/move-projects/testing-move-stdlib/sources/hash.move, tests/assets/move-projects/testing-move-stdlib/sources/option.move, tests/assets/move-projects/testing-move-stdlib/sources/string.move, tests/assets/move-projects/testing-move-stdlib/sources/type_name.move, tests/assets/move-projects/testing-move-stdlib/sources/unit_test.move, tests/assets/move-projects/testing-move-stdlib/sources/vector.move, tests/assets/move-projects/testing-substrate-stdlib/Move.toml, tests/assets/move-projects/testing-substrate-stdlib/README.md, tests/assets/move-projects/testing-substrate-stdlib/sources/balance.move, tests/mock.rs, tests/update.rs
- Added an improved solution for `new_test_ext` -> `ExtBuilder`, but both are still usable
- Added fake standard libraries for testing purposes in `tests/assets/move-projects`
- Implemented two unit tests for extrinsic call `update_stdlib`
=> feat: add tests for extrinsic update_stdlib

README.md
URL fixes for:
- the tutorial
- the Move book
=> doc: fix broken links in readme

Dockerfile
- Until now we used two different base images for building the node and for the final image
- This can lead to an error when the two base images update to different C-library versions
- Switched both base images to Ubuntu-22.04 to avoid that effect
=> chore: harmonise base images to avoid different c-lib versions

doc/tech_guide.md
Replace hints for command adjustment options with hints on how to start the container for easy connecting.
=> doc: add an important hint for usage with docker

src/lib.rs, tests/address.rs, tests/publish.rs
- Implemented memory protection for Move core address
- Protection mechanism is now within `to_move_address` method
- The two methods `raw_publish_module` and `raw_publish_bundle` now getting `AccountAddress` passed instead of `T::AccountID`
=> feat: add memory protection for core address

Cargo.toml, pallet/Cargo.toml, pallet/src/lib.rs, pallet/src/mock.rs, pallet/src/signer.rs, pallet/src/tests/assets/move-projects/multiple-signers/build.sh, pallet/src/tests/assets/move-projects/smove-build-all.sh, pallet/src/tests/assets/move-projects/smove-clean-all.sh, pallet/src/tests/signer.rs, pallet/src/weights.rs
- implemented hook `on_idle` as a clean-up mechanism for old multi-sign requests
- added two unit tests for multi-signing situations with event-checking
- restored state of unit tests with eight signers and updated them to the current state of development
=> feat: implement clean up mechanism and add unit tests

.github/workflows/common.yml, pallet/src/lib.rs, pallet/src/mock.rs, pallet/src/signer.rs, pallet/src/tests/signer.rs, pallet/src/tests/update_stdlib.rs
- implemented currency locking in case of multi-signer execution requests
- extended existing unit tests for checking this implementation
- added a new unit test about checking the cheque limit in case of multi-signer requests
- fixed the GitHub CI action because otherwise, the checks wouldn't have been triggered in this PR
=> feat: implement currency locking and extend testing

pallet/src/lib.rs, pallet/src/mock.rs, pallet/src/weights.rs
- Replaced chore mechanism on `MultisigStorage` with a new one to optimise average storage access rate
=> feat: optimise storage access rate chore mechanism

pallet/src/api.rs, rpc/src/lib.rs
- when estimating gas for a script execution, two unnecessary parameters are passed
- this PR removes them from the RPC-ABI
=> feat: remove unnecessary parameters for gas estimation

pallet/src/balance.rs, pallet/src/lib.rs, pallet/src/mock.rs, pallet/src/signer.rs, pallet/src/tests/signer.rs
- Optimization included.
- Included new tests.
- Fixed one tiny bug that allowed users to fill out the multisig storage when the wrong user tried to sign the single signer script.
=> refactor: optimise solo signer in regards to multisig functionality

pallet/src/assets/move-projects/car-wash-example/build.sh, pallet/src/assets/move-projects/car-wash-example/estimate-gas-scripts.sh, pallet/src/assets/move-projects/car-wash-example/hints.md, pallet/src/assets/move-projects/multiple-signers/estimate.init_module.sh, pallet/src/assets/move-projects/multiple-signers/estimate.publish_module.sh, pallet/src/assets/move-projects/multiple-signers/estimate.rent_apartment.sh, pallet/src/assets/move-projects/multiple-signers/hints.md, pallet/src/assets/move-projects/smove-build-all.sh, pallet/src/assets/move-projects/smove-script-weights-exec.sh, pallet/src/assets/move-projects/smove-script-weights-init.sh
- all build-scripts are now named `build.sh`
- main scrips in `move-projects` do now check if there is such a `build.rs` before applying `smove build/bundle`
- helper scripts that do work only in certain conditions, are transformed into hint files `Hints.md`
=> feat: harmonised helper scripts and removed scripts with requirements

pallet/src/assets/move-projects/balance/Move.toml, pallet/src/assets/move-projects/car-wash-example/Move.toml, pallet/src/assets/move-projects/multiple-signers/Move.toml
- harmonise naming style in Move-stdlibs, here: `SubstrateStdlib`
=> chore: harmonise naming style in Move stdlibs

pallet/build.rs, pallet/src/assets/move-projects/gas-costs/sources/ModuleNotModule.move, pallet/src/assets/move-projects/gas-costs/sources/TheModule.move, pallet/src/assets/move-projects/smove-build-all.sh, pallet/src/assets/move-projects/smove-module-weights.sh, pallet/src/tests/gas_costs.rs
- Move-project `gas-costs` now becomes a regular asset because compilation time is acceptable
- added two more scripts to evaluate gas cost differences when using modules and without
=> feat: new gas cost measurement scripts

pallet/src/api.rs, pallet/src/lib.rs, rpc/src/lib.rs
- removed RPC methods about gas-to-weight relations since they are not fixed
- added total weight including gas costs to `MoveApiEstimation`
=> feat: remove rpc methods about gas weight relations

pallet/src/api.rs, rpc/src/lib.rs
The weight info used in `Estimation` struct for estimate RPC API.
=> chore: update rpc with missing weight info

pallet/src/lib.rs, pallet/src/signer.rs, pallet/src/tests/signer.rs
- we remove the `UserHasAlreadySigned`-event to introduce a simpler and more comfortable approach
- provide the possibility to update the signing data in case of multiple signing execution requests
=> feat: extend unit test to cover multi-signer execution fail

pallet/src/assets/move-projects/gas-costs-bundles/build.sh, pallet/src/assets/move-projects/gas-costs-bundles/clean.sh, pallet/src/assets/move-projects/smove-build-all.sh, pallet/src/assets/move-projects/smove-clean-all.sh
- Move project `gas-costs-bundle` was missing in the build process
- modified shell scripts for building and cleaning to work properly
=> fix: add project gas-costs-bundle to build process for benchmarks

pallet/src/benchmarking.rs, pallet/src/tests/gas_costs.rs
Otherwise the test might attempt to add with overflow.
=> fix: lower the test balance in benchmark tests

pallet/src/assets/move-projects/gas-costs-bundles/build.sh, pallet/src/assets/move-projects/gas-costs/gen_cal_scripts.sh
Seems like the behavior in `sh` is not aligned between OSX and Linux. On Linux, sh script functions are not supposed to be prefixed with the `function` keyword.
=> fix: sh functions do not use `function` prefix on Linux

Dockerfile
- removed dev-setup from substrate-move
- removed checkout of substrate-move
- added two packages on Linux setup instead
- removed `--feature runtime-benchmarks` from node compilation
=> fix: update dockerfile and simplify it

doc/tech_guide.md
- added two sentences about compilation with/without feature `runtime-benchmarks`
=> doc: add notes about runtime-benchmarks feature

doc/tech_guide.md
I’ve updated the template to use pallet-move dependencies from a remote Git repository instead of local references, making it easier for others to collaborate and reproduce the project. 
This is the corresponding update on the docs to reflect that change.
=> docs: update docs to reflect the chances
