eigerco/pallet-move

Cargo.toml
src/address.rs
src/lib.rs

Conversion functions between Substrate and MoveVM address formats.

feat: MoveVM <-> Substrate address converter

---

src/lib.rs
tests/execute.rs
tests/mock.rs
tests/modules.rs
tests/publish.rs

- A few new tests for gas estimation.
- Also included:
- [chore: adapt API to use GasAmount](https://github.com/eigerco/pallet-move/commit/b38c7c5f09ec4899ef709542d6083e9685747134)

 feat(test): add all publish/bundle tests 

---

src/lib.rs

I would like to write some tests for this in some future PRs.

feat: init stdlib within the genesis config

---

src/lib.rs

Added an option to override the substrate-stdlib bundle.

chore: update genesis cfg with substrate-stdlib opt

---

src/balance.rs
src/lib.rs

Full balance implementation is still to be done.

chore: basic balance trait impl

---

Cargo.toml
src/lib.rs
tests/assets/move-projects/get-resource/Move.toml
tests/assets/move-projects/get-resource/scripts/Count.move
tests/assets/move-projects/get-resource/scripts/CreateCounter.move
tests/assets/move-projects/get-resource/sources/Counter.move
tests/assets/move-projects/smove-build-all.sh
tests/execute.rs

Implement tests `execute.rs`:
- `execute_script_storage_correct`
- `execute_script_insufficient_gas`
- `execute_script_corrupted_bytecode`

test: implement remaining execute tests

---

doc/tutorial.md

- Improved intro sections.
- Improved final "finalizing the tutorial" section.
- Put images in tables so it looks nicer.

doc: final tutorial polishing

---

README.md
doc/final-design.md
doc/milestone-deliverables/M1.md
doc/milestone-deliverables/M2.md
doc/milestone-deliverables/README.md
doc/milestone-deliverables/m1-testing-guide.md
doc/tech_guide.md
doc/tutorial.md

- small improvements in readme, design document
- deliverable folder and all documents related to deliverables
- old testing guide (M1) deprecated

doc: deliverables docs

---

doc/tech_guide.md
src/benchmarking.rs

- Updated sources and parameters in extrinsic wrappers in `benchmarking.rs`
- Updated bash command in tech-guide for running the pallet benchmarking with template-node

feat: update benchmarking methods

---

Cargo.toml
src/balance.rs
src/lib.rs
src/result.rs
src/signer.rs
src/weights.rs
tests/mock.rs
tests/signer.rs

- Basic implementation for feature multi-signer / multi-signature in pallet-move
- Defined new events and error messages
- Adapted mockup so that tests are working again
- Modified `ScriptSignatureHandler`

feat: basic implementation for multi-signature feature

---

src/lib.rs
src/mock.rs
src/signer.rs
src/tests/signer.rs

- Cleanup usage of `T::AccountID` and `AccountAddress` in `ScriptSignatureHandler`
- Updated existing unit tests

feat: optimize multi signer feature and update existing tests

---

pallet/src/balance.rs
pallet/src/lib.rs
pallet/src/mock.rs
pallet/src/signer.rs

- Introduced new associated type `CurrencyBalance` to simplify trait bounds over multiple source files
- Harmonised data type for balances over adapters `BalanceAdapter` and `ScriptSignatureHandler`

feat: unique usage of balance type in interfaces

---

pallet/src/tests/assets/move-projects/multiple-signers/estimate.sh

. Optimised a helper script for an existing example

chore: update helper script parameters in example move project

---

doc/tech_guide.md
pallet/src/lib.rs
pallet/src/mock.rs

- renamed pallet config constant `MaxLifetimeRequests` to `MultisigReqExpireTime`

feat: optimise pallet config constant's name

---

doc/tutorial.md
pallet/src/tests/assets/move-projects/car-wash-example/hints.md
pallet/src/tests/assets/move-projects/multiple-signers/estimate.init_module.sh
pallet/src/tests/assets/move-projects/multiple-signers/estimate.rent_apartment.sh

- updated smove instructions and helper scripts due to changed RPC-ABI

chore: update smove instructions due to changed rpc abi

---

pallet/src/api.rs
pallet/src/lib.rs
rpc/src/lib.rs

- moved RPC method implementation from template-node to pallet

feat: implement rpc functionality within the pallet

---

pallet/src/assets/move-projects/move-basics/sources/Prohibited.move
pallet/src/assets/move-projects/prohibited-bundle/Move.toml
pallet/src/assets/move-projects/prohibited-bundle/sources/Prohibited1.move
pallet/src/assets/move-projects/prohibited-bundle/sources/Prohibited2.move
pallet/src/assets/move-projects/smove-build-all.sh
pallet/src/mock_utils.rs
pallet/src/tests/address.rs
pallet/src/tests/publish.rs

- added more generic unit tests about publishing a module or a bundle to the protected memory area

feat: add tests for publishing in protected memory area

---

pallet/src/assets/move-projects/base58_smove_build/Move.toml
pallet/src/assets/move-projects/base58_smove_build/sources/BobBase58.move
pallet/src/assets/move-projects/smove-build-all.sh
pallet/src/assets/move-projects/smove-clean-all.sh
pallet/src/tests/publish.rs

- added unit-test for testing publishing a module with a base58 encoded address

feat: add publish module unit test with base58

---

README.md
doc/stdlib-doc.md

- how to add new stdlib modules
- how to update stdlib module during the runtime with the extrinsic

doc: add stdlib info

---

Cargo.toml
pallet/src/mock.rs
rpc/src/lib.rs

- upgrade Substrate dependencies
- slight modifications on RPC implementation

feat: upgrade to polkadot-v1.12.0

---

doc/final-design.md
doc/gas-handling.md
doc/stdlib-doc.md
doc/tech_guide.md
doc/tutorial-multi-signer.md
doc/tutorial.md
pallet/src/assets/move-projects/smove-clean-all.sh
pallet/src/mock_utils.rs
pallet/src/signer.rs

- fixes for broken url
- updated wrong info
- tiny improvements

doc: small updates
